package com.wre.model;
// Generated Apr 27, 2016 3:07:21 PM by Hibernate Tools 4.3.1


import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.wre.common.util.WREConstants;

/**
 * Agenda generated by hbm2java
 */
@Entity
@Table(name="agenda"
    ,catalog=WREConstants.CATALOG
)
public class Agenda  implements java.io.Serializable {


     private Long agenId;
     private Event event;
     private String agenTitle;
     private String agenDesc;
     private String agenStartTime;
     private String agenEndTime;
     private String agenBy;

    public Agenda() {
    }

    public Agenda(Event event, String agenTitle, String agenDesc, String agenStartTime, String agenEndTime, String agenBy) {
       this.event = event;
       this.agenTitle = agenTitle;
       this.agenDesc = agenDesc;
       this.agenStartTime = agenStartTime;
       this.agenEndTime = agenEndTime;
       this.agenBy = agenBy;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Agen_ID", unique=true, nullable=false)
    public Long getAgenId() {
        return this.agenId;
    }
    
    public void setAgenId(Long agenId) {
        this.agenId = agenId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Event_ID")
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }

    
    @Column(name="Agen_Title", length=100)
    public String getAgenTitle() {
        return this.agenTitle;
    }
    
    public void setAgenTitle(String agenTitle) {
        this.agenTitle = agenTitle;
    }

    
    @Column(name="Agen_Desc", length=65535)
    public String getAgenDesc() {
        return this.agenDesc;
    }
    
    public void setAgenDesc(String agenDesc) {
        this.agenDesc = agenDesc;
    }

    
    @Column(name="Agen_Start_Time", length=20)
    public String getAgenStartTime() {
        return this.agenStartTime;
    }
    
    public void setAgenStartTime(String agenStartTime) {
        this.agenStartTime = agenStartTime;
    }

    
    @Column(name="Agen_End_Time", length=20)
    public String getAgenEndTime() {
        return this.agenEndTime;
    }
    
    public void setAgenEndTime(String agenEndTime) {
        this.agenEndTime = agenEndTime;
    }

    
    @Column(name="Agen_By", length=100)
    public String getAgenBy() {
        return this.agenBy;
    }
    
    public void setAgenBy(String agenBy) {
        this.agenBy = agenBy;
    }




}


