package com.wre.model;
// Generated Apr 27, 2016 3:07:21 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Newsfeed generated by hbm2java
 */
@Entity
@Table(name="newsfeed"
    ,catalog="wre_dev"
)
public class Newsfeed  implements java.io.Serializable {


     private Long newsFeedId;
     private Event event;
     private String newsTitle;
     private String newsDesc;
     private Date newsDate;

    public Newsfeed() {
    }

    public Newsfeed(Event event, String newsTitle, String newsDesc, Date newsDate) {
       this.event = event;
       this.newsTitle = newsTitle;
       this.newsDesc = newsDesc;
       this.newsDate = newsDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="NewsFeed_ID", unique=true, nullable=false)
    public Long getNewsFeedId() {
        return this.newsFeedId;
    }
    
    public void setNewsFeedId(Long newsFeedId) {
        this.newsFeedId = newsFeedId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Event_ID")
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }

    
    @Column(name="News_Title", length=100)
    public String getNewsTitle() {
        return this.newsTitle;
    }
    
    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle;
    }

    
    @Column(name="News_Desc", length=65535)
    public String getNewsDesc() {
        return this.newsDesc;
    }
    
    public void setNewsDesc(String newsDesc) {
        this.newsDesc = newsDesc;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="News_Date", length=19)
    public Date getNewsDate() {
        return this.newsDate;
    }
    
    public void setNewsDate(Date newsDate) {
        this.newsDate = newsDate;
    }




}


