package com.wre.model;
// Generated Apr 27, 2016 3:07:21 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Speaker generated by hbm2java
 */
@Entity
@Table(name="speaker"
    ,catalog="wre_dev"
)
public class Speaker  implements java.io.Serializable {


     private Long speakerId;
     private Event event;
     private String speakerName;
     private String location;
     private String title;
     private String desc;
     private String rating;

    public Speaker() {
    }

    public Speaker(Event event, String speakerName, String location, String title, String desc, String rating) {
       this.event = event;
       this.speakerName = speakerName;
       this.location = location;
       this.title = title;
       this.desc = desc;
       this.rating = rating;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Speaker_ID", unique=true, nullable=false)
    public Long getSpeakerId() {
        return this.speakerId;
    }
    
    public void setSpeakerId(Long speakerId) {
        this.speakerId = speakerId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Event_ID")
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }

    
    @Column(name="Speaker_Name", length=65535)
    public String getSpeakerName() {
        return this.speakerName;
    }
    
    public void setSpeakerName(String speakerName) {
        this.speakerName = speakerName;
    }

    
    @Column(name="Location", length=100)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    
    @Column(name="Title", length=200)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="Desc", length=65535)
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }

    
    @Column(name="Rating", length=20)
    public String getRating() {
        return this.rating;
    }
    
    public void setRating(String rating) {
        this.rating = rating;
    }




}


