package com.wre.model;
// Generated Apr 27, 2016 3:07:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SurveyQuestion generated by hbm2java
 */
@Entity
@Table(name="survey_question"
    ,catalog="wre_dev"
)
public class SurveyQuestion  implements java.io.Serializable {


     private Long questionId;
     private AppIdentifier appIdentifier;
     private Event event;
     private User user;
     private String question;
     private String optionA;
     private String optionB;
     private String optionC;
     private String optionD;
     private String answer;
     private Set<SurveyQuestionAnswer > surveyQuestionAnswers = new HashSet(0);

    public SurveyQuestion() {
    }

    public SurveyQuestion(AppIdentifier appIdentifier, Event event, User user, String question, String optionA, String optionB, String optionC, String optionD, String answer, Set<SurveyQuestionAnswer> surveyQuestionAnswers) {
       this.appIdentifier = appIdentifier;
       this.event = event;
       this.user = user;
       this.question = question;
       this.optionA = optionA;
       this.optionB = optionB;
       this.optionC = optionC;
       this.optionD = optionD;
       this.answer = answer;
       this.surveyQuestionAnswers = surveyQuestionAnswers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Question_ID", unique=true, nullable=false)
    public Long getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Question_Type_ID")
    public AppIdentifier getAppIdentifier() {
        return this.appIdentifier;
    }
    
    public void setAppIdentifier(AppIdentifier appIdentifier) {
        this.appIdentifier = appIdentifier;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Event_ID")
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Create_By")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="Question", length=65535)
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }

    
    @Column(name="Option_A", length=200)
    public String getOptionA() {
        return this.optionA;
    }
    
    public void setOptionA(String optionA) {
        this.optionA = optionA;
    }

    
    @Column(name="Option_B", length=200)
    public String getOptionB() {
        return this.optionB;
    }
    
    public void setOptionB(String optionB) {
        this.optionB = optionB;
    }

    
    @Column(name="Option_C", length=200)
    public String getOptionC() {
        return this.optionC;
    }
    
    public void setOptionC(String optionC) {
        this.optionC = optionC;
    }

    
    @Column(name="Option_D", length=200)
    public String getOptionD() {
        return this.optionD;
    }
    
    public void setOptionD(String optionD) {
        this.optionD = optionD;
    }

    
    @Column(name="Answer", length=100)
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="surveyQuestion")
    public Set<SurveyQuestionAnswer> getSurveyQuestionAnswers() {
        return this.surveyQuestionAnswers;
    }
    
    public void setSurveyQuestionAnswers(Set<SurveyQuestionAnswer> surveyQuestionAnswers) {
        this.surveyQuestionAnswers = surveyQuestionAnswers;
    }




}


