package com.wre.model;
// Generated Apr 27, 2016 3:07:21 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SurveyQuestionAnswer generated by hbm2java
 */
@Entity
@Table(name="survey_question_answer"
    ,catalog="wre_dev"
)
public class SurveyQuestionAnswer  implements java.io.Serializable {


     private Long surQueAnsId;
     private Event event;
     private Participants participants;
     private SurveyQuestion surveyQuestion;
     private String participantAnswer;

    public SurveyQuestionAnswer() {
    }

    public SurveyQuestionAnswer(Event event, Participants participants, SurveyQuestion surveyQuestion, String participantAnswer) {
       this.event = event;
       this.participants = participants;
       this.surveyQuestion = surveyQuestion;
       this.participantAnswer = participantAnswer;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Sur_Que_Ans_ID", unique=true, nullable=false)
    public Long getSurQueAnsId() {
        return this.surQueAnsId;
    }
    
    public void setSurQueAnsId(Long surQueAnsId) {
        this.surQueAnsId = surQueAnsId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Event_ID")
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Participant_ID")
    public Participants getParticipants() {
        return this.participants;
    }
    
    public void setParticipants(Participants participants) {
        this.participants = participants;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Question_ID")
    public SurveyQuestion getSurveyQuestion() {
        return this.surveyQuestion;
    }
    
    public void setSurveyQuestion(SurveyQuestion surveyQuestion) {
        this.surveyQuestion = surveyQuestion;
    }

    
    @Column(name="Participant_Answer", length=200)
    public String getParticipantAnswer() {
        return this.participantAnswer;
    }
    
    public void setParticipantAnswer(String participantAnswer) {
        this.participantAnswer = participantAnswer;
    }




}


