package com.wre.model;
// Generated Apr 27, 2016 3:07:21 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.wre.common.util.WREConstants;

/**
 * AppIdentifierGrp generated by hbm2java
 */
@Entity
@Table(name="app_identifier_grp"
    ,catalog=WREConstants.CATALOG
)
public class AppIdentifierGrp  implements java.io.Serializable {


     private Long appIdentifierGrpId;
     private String groupName;
     private String groupDesc;
     private Date createdOn;
     private Date updatedOn;
     private Set<AppIdentifier> appIdentifiers = new HashSet(0);

    public AppIdentifierGrp() {
    }

    public AppIdentifierGrp(String groupName, String groupDesc, Date createdOn, Date updatedOn, Set<AppIdentifier> appIdentifiers) {
       this.groupName = groupName;
       this.groupDesc = groupDesc;
       this.createdOn = createdOn;
       this.updatedOn = updatedOn;
       this.appIdentifiers = appIdentifiers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="AppIdentifier_Grp_ID", unique=true, nullable=false)
    public Long getAppIdentifierGrpId() {
        return this.appIdentifierGrpId;
    }
    
    public void setAppIdentifierGrpId(Long appIdentifierGrpId) {
        this.appIdentifierGrpId = appIdentifierGrpId;
    }

    
    @Column(name="Group_Name", length=100)
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    
    @Column(name="Group_Desc", length=250)
    public String getGroupDesc() {
        return this.groupDesc;
    }
    
    public void setGroupDesc(String groupDesc) {
        this.groupDesc = groupDesc;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_On", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Updated_On", length=19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="appIdentifierGrp")
    public Set<AppIdentifier> getAppIdentifiers() {
        return this.appIdentifiers;
    }
    
    public void setAppIdentifiers(Set<AppIdentifier> appIdentifiers) {
        this.appIdentifiers = appIdentifiers;
    }




}


