package com.wre.model;
// Generated Apr 27, 2016 3:07:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.wre.common.util.WREConstants;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name="client"
    ,catalog=WREConstants.CATALOG
)
public class Client  implements java.io.Serializable {


     private Long clientId;
     private String clientName;
     private String address;
     private String description;
     private String staus;
     private Set<Event> events = new HashSet(0);
     private Set<User> users = new HashSet(0);

    public Client() {
    }

    public Client(String clientName, String address, String description, String staus, Set<Event> events, Set<User> users) {
       this.clientName = clientName;
       this.address = address;
       this.description = description;
       this.staus = staus;
       this.events = events;
       this.users = users;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Client_ID", unique=true, nullable=false)
    public Long getClientId() {
        return this.clientId;
    }
    
    public void setClientId(Long clientId) {
        this.clientId = clientId;
    }

    
    @Column(name="Client_Name", length=100)
    public String getClientName() {
        return this.clientName;
    }
    
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    
    @Column(name="Address", length=65535)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="Description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="Staus", length=20)
    public String getStaus() {
        return this.staus;
    }
    
    public void setStaus(String staus) {
        this.staus = staus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="client")
    public Set<Event> getEvents() {
        return this.events;
    }
    
    public void setEvents(Set<Event> events) {
        this.events = events;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="client")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


