package com.wre.model;

//Generated 6 Jun, 2016 11:27:28 AM by Hibernate Tools 4.3.1


// Generated 14 Jun, 2016 12:36:05 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.wre.common.util.WREConstants;

/**
 * ContactDetails generated by hbm2java
 */
@Entity
@Table(name="contact_details",catalog=WREConstants.CATALOG)
public class ContactDetails  implements java.io.Serializable {


     private Long contactId;
     private Event event;
     private Participants participants;
     private String contactName;
     private String contactEmail;
     private String contactMobile;
     private String contactAlternateMobile;
     private String helpText;

    public ContactDetails() {
    }

    public ContactDetails(Event event, Participants participants, String contactName, String contactEmail, String contactMobile, String contactAlternateMobile, String helpText) {
       this.event = event;
       this.participants = participants;
       this.contactName = contactName;
       this.contactEmail = contactEmail;
       this.contactMobile = contactMobile;
       this.contactAlternateMobile = contactAlternateMobile;
       this.helpText = helpText;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Contact_ID", unique=true, nullable=false)
    public Long getContactId() {
        return this.contactId;
    }
    
    public void setContactId(Long contactId) {
        this.contactId = contactId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Event_ID")
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Participant_ID")
    public Participants getParticipants() {
        return this.participants;
    }
    
    public void setParticipants(Participants participants) {
        this.participants = participants;
    }

    
    @Column(name="Contact_Name", length=200)
    public String getContactName() {
        return this.contactName;
    }
    
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    
    @Column(name="Contact_Email", length=50)
    public String getContactEmail() {
        return this.contactEmail;
    }
    
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }

    
    @Column(name="Contact_Mobile", length=20)
    public String getContactMobile() {
        return this.contactMobile;
    }
    
    public void setContactMobile(String contactMobile) {
        this.contactMobile = contactMobile;
    }

    
    @Column(name="Contact_Alternate_Mobile", length=20)
    public String getContactAlternateMobile() {
        return this.contactAlternateMobile;
    }
    
    public void setContactAlternateMobile(String contactAlternateMobile) {
        this.contactAlternateMobile = contactAlternateMobile;
    }

    
    @Column(name="Help_Text", length=65535)
    public String getHelpText() {
        return this.helpText;
    }
    
    public void setHelpText(String helpText) {
        this.helpText = helpText;
    }




}