package com.wre.model;
// Generated Apr 27, 2016 3:07:21 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.wre.common.util.WREConstants;

/**
 * EventParticipant generated by hbm2java
 */
@Entity
@Table(name="event_participant"
    ,catalog=WREConstants.CATALOG
)
public class EventParticipant  implements java.io.Serializable {


     private Long eveParticipantId;
     private Event event;
     private Participants participants;
     private String status;

    public EventParticipant() {
    }

    public EventParticipant(Event event, Participants participants, String status) {
       this.event = event;
       this.participants = participants;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Eve_Participant_ID", unique=true, nullable=false)
    public Long getEveParticipantId() {
        return this.eveParticipantId;
    }
    
    public void setEveParticipantId(Long eveParticipantId) {
        this.eveParticipantId = eveParticipantId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Event_ID")
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Participant_ID")
    public Participants getParticipants() {
        return this.participants;
    }
    
    public void setParticipants(Participants participants) {
        this.participants = participants;
    }

    
    @Column(name="Status", length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


