package com.wre.model;
// Generated Apr 27, 2016 3:07:21 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EventServices generated by hbm2java
 */
@Entity
@Table(name="event_services"
    ,catalog="wre_dev"
)
public class EventServices  implements java.io.Serializable {


     private Long eventServiceId;
     private Event event;
     private Services services;
     private String status;

    public EventServices() {
    }

    public EventServices(Event event, Services services, String status) {
       this.event = event;
       this.services = services;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Event_Service_ID", unique=true, nullable=false)
    public Long getEventServiceId() {
        return this.eventServiceId;
    }
    
    public void setEventServiceId(Long eventServiceId) {
        this.eventServiceId = eventServiceId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Event_ID")
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Service_ID")
    public Services getServices() {
        return this.services;
    }
    
    public void setServices(Services services) {
        this.services = services;
    }

    
    @Column(name="Status", length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


