package com.wre.model;
// Generated Apr 27, 2016 3:07:21 PM by Hibernate Tools 4.3.1


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Galary generated by hbm2java
 */
@Entity
@Table(name="galary"
    ,catalog="wre_dev"
)
public class Galary  implements java.io.Serializable {


     private Long glaryItemId;
     private Event event;
     private Participants participants;
     private String name;
     private String path;
     private String type;
     private String fileName;
     private Date createdDate;
     
    public Galary() {
    }

    public Galary(Event event, Participants participants, String name, String path, String type,String fileName, Date createdDate) {
       this.event = event;
       this.participants = participants;
       this.name = name;
       this.path = path;
       this.type = type;
       this.fileName=fileName;
       this.createdDate = createdDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Glary_Item_ID", unique=true, nullable=false)
    public Long getGlaryItemId() {
        return this.glaryItemId;
    }
    
    public void setGlaryItemId(Long glaryItemId) {
        this.glaryItemId = glaryItemId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Event_ID")
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Created_By")
    public Participants getParticipants() {
        return this.participants;
    }
    
    public void setParticipants(Participants participants) {
        this.participants = participants;
    }

    
    @Column(name="Name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Path", length=100)
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }

    
    @Column(name="Type", length=20)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    @Column(name="FileName", length=200)
	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

}


