package com.wre.model;



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.wre.common.util.WREConstants;

/**
* Help generated by hbm2java
*/
@Entity
@Table(name="help"
 ,catalog=WREConstants.CATALOG
)
public class Help  implements java.io.Serializable {


  private Long helpId;
  private Event event;
  private Participants participants;
  private String question;
  private String answer;

 public Help() {
 }

 public Help(Event event, Participants participants, String question, String answer) {
    this.event = event;
    this.participants = participants;
    this.question = question;
    this.answer = answer;
 }

  @Id @GeneratedValue(strategy=IDENTITY)

 
 @Column(name="Help_ID", unique=true, nullable=false)
 public Long getHelpId() {
     return this.helpId;
 }
 
 public void setHelpId(Long helpId) {
     this.helpId = helpId;
 }

@ManyToOne(fetch=FetchType.LAZY)
 @JoinColumn(name="Event_ID")
 public Event getEvent() {
     return this.event;
 }
 
 public void setEvent(Event event) {
     this.event = event;
 }

@ManyToOne(fetch=FetchType.LAZY)
 @JoinColumn(name="Paticipant_ID")
 public Participants getParticipants() {
     return this.participants;
 }
 
 public void setParticipants(Participants participants) {
     this.participants = participants;
 }

 
 @Column(name="Question", length=65535)
 public String getQuestion() {
     return this.question;
 }
 
 public void setQuestion(String question) {
     this.question = question;
 }

 
 @Column(name="Answer", length=65535)
 public String getAnswer() {
     return this.answer;
 }
 
 public void setAnswer(String answer) {
     this.answer = answer;
 }




}


