package com.wre.model;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name="rating"
    ,catalog="wre_dev"
)
public class Rating  implements java.io.Serializable {


     private Long ratingId;
     private Long sourceId;
     private Long userId;
     private Long eventId;
     private String type;



    public Rating() {
    }

    public Rating(Long ratingId,Long sourceId,Long userId,Long eventId,String type) {
       this.ratingId = ratingId;
       this.sourceId = sourceId;
       this.userId = userId;
       this.eventId = eventId;
       this.type = type;


    }
   


    
  @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="Rating_ID", unique=true, nullable=false)
	public Long getRatingId() {
		return ratingId;
	}

	public void setRatingId(Long ratingId) {
		this.ratingId = ratingId;
	}


    @Column(name = "Source_ID")
	public Long getSourceId() {
		return sourceId;
	}

	public void setSourceId(Long sourceId) {
		this.sourceId = sourceId;
	}
	   @Column(name = "User_ID")
	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}
	   @Column(name = "Event_ID")
	public Long getEventId() {
		return eventId;
	}

	public void setEventId(Long eventId) {
		this.eventId = eventId;
	}
	@Column(name = "Type", length = 20)
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}





}


