package com.wre.model;
// Generated Apr 27, 2016 3:07:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.wre.common.util.WREConstants;

/**
 * Services generated by hbm2java
 */
@Entity
@Table(name="services"
    ,catalog=WREConstants.CATALOG
)
public class Services  implements java.io.Serializable {


     private Long serviceId;
     private String serviceName;
     private String serviceDesc;
     private int order;
     private Set<EventServices> eventServiceses = new HashSet(0);

    public Services() {
    }

    public Services(String serviceName, String serviceDesc, int order,Set<EventServices> eventServiceses) {
       this.serviceName = serviceName;
       this.serviceDesc = serviceDesc;
       this.order=order;
       this.eventServiceses = eventServiceses;
    }
   
     
	@Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Service_ID", unique=true, nullable=false)
    public Long getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(Long serviceId) {
        this.serviceId = serviceId;
    }

    
    @Column(name="Service_Name", length=100)
    public String getServiceName() {
        return this.serviceName;
    }
    
    @Column(name="Order")
    public int getOrder() {
		return order;
	}

	public void setOrder(int order) {
		this.order = order;
	}

    
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    
    @Column(name="Service_Desc", length=65535)
    public String getServiceDesc() {
        return this.serviceDesc;
    }
    
    public void setServiceDesc(String serviceDesc) {
        this.serviceDesc = serviceDesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="services")
    public Set<EventServices> getEventServiceses() {
        return this.eventServiceses;
    }
    
    public void setEventServiceses(Set<EventServices> eventServiceses) {
        this.eventServiceses = eventServiceses;
    }




}


