package com.wre.model;

//Generated 16 Jun, 2016 12:13:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.wre.common.util.WREConstants;

/**
* Speaker generated by hbm2java
*/
@Entity
@Table(name="speaker",catalog=WREConstants.CATALOG)
public class Speaker  implements java.io.Serializable {


  private Long speakerId;
  private Event event;
  private String speakerName;
  private String location;
  private String title;
  private String rating;
  private String description;
  private String fileName;
  private Set<ParticipantQuries> participantQurieses = new HashSet<ParticipantQuries>(0);

 public Speaker() {
 }

 public Speaker(Event event, String speakerName, String location, String title, String rating, String description, String fileName, Set<ParticipantQuries> participantQurieses) {
    this.event = event;
    this.speakerName = speakerName;
    this.location = location;
    this.title = title;
    this.rating = rating;
    this.description = description;
    this.fileName = fileName;
    this.participantQurieses = participantQurieses;
 }

  @Id @GeneratedValue(strategy=IDENTITY)

 
 @Column(name="Speaker_ID", unique=true, nullable=false)
 public Long getSpeakerId() {
     return this.speakerId;
 }
 
 public void setSpeakerId(Long speakerId) {
     this.speakerId = speakerId;
 }

@ManyToOne(fetch=FetchType.LAZY)
 @JoinColumn(name="Event_ID")
 public Event getEvent() {
     return this.event;
 }
 
 public void setEvent(Event event) {
     this.event = event;
 }

 
 @Column(name="Speaker_Name", length=200)
 public String getSpeakerName() {
     return this.speakerName;
 }
 
 public void setSpeakerName(String speakerName) {
     this.speakerName = speakerName;
 }

 
 @Column(name="Location", length=100)
 public String getLocation() {
     return this.location;
 }
 
 public void setLocation(String location) {
     this.location = location;
 }

 
 @Column(name="Title", length=200)
 public String getTitle() {
     return this.title;
 }
 
 public void setTitle(String title) {
     this.title = title;
 }

 
 @Column(name="Rating", length=20)
 public String getRating() {
     return this.rating;
 }
 
 public void setRating(String rating) {
     this.rating = rating;
 }

 
 @Column(name="Description")
 public String getDescription() {
     return this.description;
 }
 
 public void setDescription(String description) {
     this.description = description;
 }

 
 @Column(name="FileName", length=200)
 public String getFileName() {
     return this.fileName;
 }
 
 public void setFileName(String fileName) {
     this.fileName = fileName;
 }

@OneToMany(fetch=FetchType.LAZY, mappedBy="speaker")
 public Set<ParticipantQuries> getParticipantQurieses() {
     return this.participantQurieses;
 }
 
 public void setParticipantQurieses(Set<ParticipantQuries> participantQurieses) {
     this.participantQurieses = participantQurieses;
 }




}


